# Generated by Django 5.1.7 on 2025-04-02 18:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_moviesmodel_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesmodel',
            name='movie_banner_desktop',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Banner Poster'),
        ),
        migrations.AlterField(
            model_name='moviesmodel',
            name='movie_poster',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Poster'),
        ),
    ]
