# Generated by Django 5.1.7 on 2025-04-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_alter_moviesmodel_movie_banner_desktop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesmodel',
            name='runtime',
            field=models.CharField(default='', max_length=50),
        ),
    ]
