# Generated by Django 5.1.7 on 2025-04-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_moviesmodel_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesmodel',
            name='ratings',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
