# Generated by Django 5.1.7 on 2025-04-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_moviesmodel_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesmodel',
            name='director',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='moviesmodel',
            name='release_year',
            field=models.CharField(default='', max_length=10),
        ),
    ]
