# Generated by Django 5.1.7 on 2025-04-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_moviesmodel_director_moviesmodel_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesmodel',
            name='review',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
