# Generated by Django 5.1.7 on 2025-04-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0007_moviesmodel_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesmodel',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
