# Generated by Django 5.1.7 on 2025-04-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0011_userpreference_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesmodel',
            name='review',
            field=models.TextField(default='None', max_length=1000),
        ),
    ]
