# Generated by Django 5.1.7 on 2025-04-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0012_alter_moviesmodel_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesmodel',
            name='user_reviews',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='moviesmodel',
            name='views',
            field=models.CharField(default=0),
        ),
    ]
